// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA165_fpQFRJySCRS_epOQ0JxlLRfskSzs',
    appId: '1:1023395212754:web:b280d165a07ad44b6aac0b',
    messagingSenderId: '1023395212754',
    projectId: 'graduation-project-11c2a',
    authDomain: 'graduation-project-11c2a.firebaseapp.com',
    storageBucket: 'graduation-project-11c2a.firebasestorage.app',
    measurementId: 'G-6BT9LBH6K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm7L505_T2RxG_ZMgvl-Us9C0e4dlz4yo',
    appId: '1:1023395212754:android:52e58b157836782f6aac0b',
    messagingSenderId: '1023395212754',
    projectId: 'graduation-project-11c2a',
    storageBucket: 'graduation-project-11c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE77ojvazlkmLlaFCiNA2qXObEQNOTJp4',
    appId: '1:1023395212754:ios:1fba3119a0f20b326aac0b',
    messagingSenderId: '1023395212754',
    projectId: 'graduation-project-11c2a',
    storageBucket: 'graduation-project-11c2a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE77ojvazlkmLlaFCiNA2qXObEQNOTJp4',
    appId: '1:1023395212754:ios:1fba3119a0f20b326aac0b',
    messagingSenderId: '1023395212754',
    projectId: 'graduation-project-11c2a',
    storageBucket: 'graduation-project-11c2a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA165_fpQFRJySCRS_epOQ0JxlLRfskSzs',
    appId: '1:1023395212754:web:572c01b086e1e19a6aac0b',
    messagingSenderId: '1023395212754',
    projectId: 'graduation-project-11c2a',
    authDomain: 'graduation-project-11c2a.firebaseapp.com',
    storageBucket: 'graduation-project-11c2a.firebasestorage.app',
    measurementId: 'G-RV6Q752VES',
  );
}
